language: ruby
rvm:
  - 2.0.0
script: bundle exec rspec spec
notifications:
  hipchat:
    rooms: 3d318fc3e1f401238a50171784b534@Enspiral Developers
    template: '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'